config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }
  root to: "homes#top"
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    resources :recipe_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recipe_tags
  has_many :tags, through: :recipe_tags
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  attachment :image
  def tags_save(tag_list)
    if self.tags != nil
      recipe_tags_records = RecipeTag.where(recipe_id: self.id)
      recipe_tags_records.destroy_all
    end
    tag_list.each do |tag|
      inspected_tag = Tag.where(tag_name: tag).first_or_create
      self.tags << inspected_tag
    end

  end
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags
  has_many :recipes, through: :recipe_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
  has_many :recipe_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def set_search
    @search = Recipe.ransack(params[:q])
    @search_recipes = @search.result.page(params[:page]).reverse_order
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    recipe = Recipe.find(params[:recipe_id])
    favorite = current_user.favorites.new(recipe_id: recipe.id)
    favorite.save
    redirect_to recipe_path(recipe)
  end

  def destroy
    recipe = Recipe.find(params[:recipe_id])
    favorite = current_user.favorites.find_by(recipe_id: recipe.id)
    favorite.destroy
    redirect_to recipe_path(recipe)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @recipes = Recipe.last(4)
  end

end

app/controllers/recipe_comments_controller.rb
class RecipeCommentsController < ApplicationController
  def create
    recipe = Recipe.find(params[:recipe_id])
    comment = current_user.recipe_comments.new(recipe_comment_params)
    comment.recipe_id = recipe.id
    comment.save
    redirect_to recipe_path(recipe)
  end

  def destroy
    RecipeComment.find_by(id: params[:id]).destroy
    redirect_to recipe_path(params[:recipe_id])
  end
  private

  def recipe_comment_params
    params.require(:recipe_comment).permit(:comment, :rate)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end
  def index
    @recipes = Recipe.page(params[:page]).reverse_order
  end
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_tags = @recipe.tags
    @recipe_comment = RecipeComment.new
  end
  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
     render :edit
    else
     redirect_to recipes_path, notice: "ほかのユーザーのレシピは編集できません。"
    end
  end
  def update
    @recipe = Recipe.find(params[:id])
    tag_list = params[:recipe][:tag_names].split(",")
    @recipe.tags_save(tag_list)
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe.id), notice: "編集しました。"
  end
  def create
    @recipe = Recipe.new(recipe_params)
    tag_list = params[:recipe][:tag_names].split(nil)
    @recipe.tags_save(tag_list)
    @recipe.user_id = current_user.id
    @recipe.save
    redirect_to recipes_path, notice: "登録しました."
  end
  def delete
  end
  
  private
  def recipe_params
    params.require(:recipe).permit(:title, :image, :foodstuff, :instructions, :impression, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @allrecipes = @user.recipes.count
  end
  def index
    @users = User.page(params[:page]).reverse_order
  end
  def edit
    @user = User.find(params[:id])
    if @user == current_user
     render :edit
    else
     redirect_to users_path, notice: "ほかのユーザー情報は編集できません。"
    end
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user), notice: "編集しました。"
  end
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipe_comments_helper.rb
module RecipeCommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <h4 class="col-md-4 offset-md-3"><u><strong>レシピ編集</strong></u></h4>
    </div>
    <div class="row justify-content-center">
      <%= form_with model:@recipe, local:true do |f| %>
        <table class="table table-borderless table_border_radius">
          <tr class="form-group">
              <th><%= f.label :title,"レシピタイトル", class:"pt-2 col-form-label" %></th>
              <td><%= f.text_field :title, class:"form-control" %></td>
          </tr>
          <tr class="form-group">
            <th><%= f.label :image ,"レシピ画像", class:"col-form-label" %></th>
              <td><%= f.attachment_field :image, class:"align-bottom" %></td>
          </tr>
          <tr class="form-group">
              <th><%= f.label :foodstuff, "食材(分量)", class:"col-form-label" %></th>
              <td><%= f.text_area :foodstuff, class:"form-control", placeholder: "例:人参(1/2本)" %></td>
          </tr>
          <tr class="form-group">
              <th><%= f.label :instructions,"手順", class:"col-form-label" %></th>
              <td><%= f.text_area :instructions, class:"form-control", placeholder: "例:1.皮をむく" %></td>
          </tr>
          <tr class="form-group">
              <th><%= f.label :impression,"作成メモ", class:"col-form-label" %></th>
              <td><%= f.text_area :impression, class:"form-control", placeholder: "例:美味しくできました。" %></td>
          </tr>
          <tr class="form-group">
            <th><%= f.label :tag_names,"レシピタグ", class:"col-form-label" %></th>
            <td><%= f.text_field :tag_names, class:"form-control", placeholder:",で区切ってください" %></td>
          </tr>
            <tr class="actions text-center">
              <th colspan="2"><%= f.submit "編集を保存する", class: "btn  btn-danger w-100" %></th>
            </tr>
        <% end %>
        </table>
    </div>
</main>

app/views/recipes/index.html.erb
<main>
  <div class="container">
    <div class="row justify-content-center">
      <% if user_signed_in? %>
        <div class="col-md-4">
          <div class="p-md-2 mt-3 p-3 border border-light rounded bg-primary">
            <h4>マイプロフィール</h4>
            <div class="col-md-6">
              <%= attachment_image_tag current_user, :profile_image, size: "150x150", fallback: "l_e_others_501.png" %>
            </div>
            <table class="table rounded border border-light">
              <tr>
                <td>名前</td>
                <td><%= current_user.name %></td>
              </tr>
              <tr>
                <td>自己紹介</td>
                <th><%= current_user.introduction %></th>
              </tr>
            </table>
            <div class="row justify-content-center">
              <%= link_to "マイプロフィールを編集する", edit_user_path(current_user.id), class: "btn btn-danger w-75 mb-2"%>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-md-8 my-3 rounded bg-primary">
        <h2><u><strong>レシピ一覧</strong></u></h2>
        <div class="row justify-content-center">
          <% @search_recipes.each do |recipe| %>
            <div class="card m-2" style="width: 12rem;">
              <%= link_to recipe_path(recipe) do %>
                <%= attachment_image_tag recipe, :image, :fill, 100, 100, class:"h-100 w-100 p-2", fallback: "l_e_others_501.png" %>
              <% end %>
              <div class="card-body">
                <div class="h5 card-title"><%= recipe.title %></div>
                <p class="card-text"><%= truncate(recipe.impression, length:20) %></p>
                <%= link_to user_path(recipe.user) do %>
                  <%= recipe.user.name %>
                <% end %>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <%= paginate @recipes %>
    </div>
  </div>
</main>

app/views/recipes/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <h4 class="col-md-4 offset-md-3"><u><strong>新規レシピ登録</strong></u></h4>
    </div>
    <div class="row justify-content-center">
      <%= form_with model:@recipe, url:recipes_path, local:true do |f| %>
        <table class="table table-borderless table_border_radius">
          <tr class="form-group">
              <th><%= f.label :title,"レシピタイトル", class:"pt-2 col-form-label" %></th>
              <td><%= f.text_field :title, class:"form-control" %></td>
          </tr>
          <tr class="form-group">
            <th><%= f.label :image ,"レシピ画像", class:"col-form-label" %></th>
              <td><%= f.attachment_field :image, class:"align-bottom" %></td>
          </tr>
          <tr class="form-group">
              <th><%= f.label :foodstuff, "食材(分量)", class:"col-form-label" %></th>
              <td><%= f.text_area :foodstuff, class:"form-control", placeholder: "例:人参(1/2本)" %></td>
          </tr>
          <tr class="form-group">
              <th><%= f.label :instructions,"手順", class:"col-form-label" %></th>
              <td><%= f.text_area :instructions, class:"form-control", placeholder: "例:1.皮をむく" %></td>
          </tr>
          <tr class="form-group">
              <th><%= f.label :impression,"作成メモ", class:"col-form-label" %></th>
              <td><%= f.text_area :impression, class:"form-control", placeholder: "例:美味しくできました。" %></td>
          </tr>
          <tr class="form-group">
            <th><%= f.label :tag_names,"レシピタグ", class:"col-form-label" %></th>
            <td><%= f.text_field :tag_names, class:"form-control", placeholder:"スペースで複数のタグ付け" %></td>
          </tr>
            <tr class="actions text-center">
              <th colspan="2"><%= f.submit "新規登録", class: "btn  btn-danger w-100" %></th>
            </tr>
        <% end %>
        </table>
    </div>
</main>

app/views/recipes/show.html.erb
<main>
  <div class="container m-auto p-4 ">
    <div class="row">
      <div class="col-md-4">
        <div class="p-2 border border-light rounded bg-primary">
        <h4>作成者プロフィール</h4>
        <div class="col-md-6 text-center">
          <%= attachment_image_tag @recipe.user, :profile_image, size: "200x200", class:"p-2", fallback: "l_e_others_501.png" %>
        </div>
        <table class="table rounded border border-light">
          <tr>
            <th>名前</td>
            <td><%= @recipe.user.name %></td>
          </tr>
          <tr>
            <th>自己紹介</th>
            <th><%= @recipe.user.introduction %></th>
          </tr>
        </table>
        <div class="row justify-content-center">
          <% if @recipe.user == current_user %>
            <%= link_to "このレシピを編集する", edit_recipe_path(@recipe), class: "btn btn-danger w-75 mb-2"%>
          <% end %>
        </div>
      </div>
      </div>
      <div class="col-md-8 p-4 border border-light rounded bg-primary">
        <h4>
          <u><strong><%= @recipe.title %></strong></u>
          <% if @recipe.favorited_by?(current_user) %>
            <%= link_to recipe_favorites_path(@recipe), method: :delete do %>
              ♥<%= @recipe.favorites.count %> いいね
            <% end %>
          <% else %>
            <%= link_to recipe_favorites_path(@recipe), method: :post do %>
              ♡<%= @recipe.favorites.count %> いいね
            <% end %>
          <% end %>
        </h4>
        <% @recipe_tags.each do |tag| %>
          <span class="m-1"><%= tag.tag_name %></span>
        <% end %>
        <div class="row justify-content-center">
          <div class="col-md-5 m-3 rounded bg-warning d-flex align-items-center justify-content-center">
            <%= attachment_image_tag @recipe, :image, size: "200x200", class:"p-2", fallback: "l_e_others_501.png" %>
          </div>
          <div class="col-md-5 rounded bg-warning m-3">
            <p>＜使用食材＞</p><br>
            <p><%= @recipe.foodstuff %></p>
          </div>
          <div class="col-md-5 rounded bg-warning m-3">
            <p>＜手順＞</p><br>
            <p><%= @recipe.instructions %></p>
          </div>
          <div class="col-md-5 rounded bg-warning m-3">
            <p>＜調理メモ＞</p><br>
            <p><%= @recipe.impression %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="offset-md-4 col-md-8 border border-light rounded bg-primary">
        <h5 class="m-3"><u>コメント</u>(<%= @recipe.recipe_comments.count %>)</h5>
          <div class="col-12">
            <% @recipe.recipe_comments.each.reverse_each do |recipe_comment| %>
              <div class="border border-dark rounded bg-warning m-3">
                <div class="col-12" >
                  <div class="py-2 border-bottom border-secondary" align="center">
                    <%= recipe_comment.comment %>
                  </div>
                </div>
                <div class="row justify-content-center">
                  <div class="col-5 m-2">
                    <div>
                      <%= link_to user_path(recipe_comment.user) do %>
                        <%= recipe_comment.user.name %>
                      <% end %>
                      <%= recipe_comment.created_at.strftime('%Y.%m.%d %H:%M') %>
                      <% if recipe_comment.user == current_user %>
                        <%= link_to "削除",recipe_recipe_comment_path(recipe_comment.recipe, recipe_comment), method: :delete %>
                      <% end %>
                    </div>
                  </div>
                <div class="col-5">
                  <div  align="right" class="recipe-evaluation" data-score="<%= recipe_comment.rate %>"></div>
                </div>
              </div>
            </div>
          <% end %>
          <script>
            $('.recipe-evaluation').raty({
              readOnly: true,
              score: function() {
                return $(this).attr('data-score');
              },
              path: '/assets/'
            });
          </script>
          <div class="border border-dark rounded bg-warning m-3">
            <%= form_with(model:[@recipe, @recipe_comment], local: true) do |f| %>
              <h4 class="my-3 mx-5">
                <u>新規コメント</u>
              </h4>
              <div class="form-group text-center">
                <div class="col-md-6 offset-md-3">
                  <%= f.text_area :comment, rows:'5',class:"form-control w-100", placeholder: "コメントをここに" %>
                  <div id="evaluate_stars">
                    <label>評価</label>
                  </div>
                  <%= f.submit "送信する", class: "btn btn-danger w-50 my-2" %>
                </div>
              </div>
            <% end %>
            <script>
            $('#evaluate_stars').raty({
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              scoreName: 'recipe_comment[rate]',
              half: true
              });
            </script>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>