config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }
  root to: "homes#top"
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    resources :recipe_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
  has_many :recipe_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
   super
   WelcomeMailer.with(user: @user).welcome_email.deliver_later
  end


  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @allrecipes = @user.recipes.count
  end
  def index
    @users = User.page(params[:page]).reverse_order
  end
  def edit
    @user = User.find(params[:id])
    if @user == current_user
     render :edit
    else
     redirect_to users_path, notice: "ほかのユーザー情報は編集できません。"
    end
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user), notice: "編集しました。"
  end
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <h4 class="col-md-4 offset-md-3"><u><strong>プロフィール編集</strong></u></h4>
    </div>
    <div class="row justify-content-center">
      <%= form_with model:@user, local:true do |f| %>
        <table class="table table-borderless table_border_radius">
          <tr class="form-group">
              <th><%= f.label :name, "名前", class:"pt-2 col-form-label" %></th>
              <td><%= f.text_field :name, class:"form-control" %></td>
          </tr>
          <tr class="form-group">
            <th><%= f.label :image ,"プロフィール画像", class:"col-form-label" %></th>
              <td><%= f.attachment_field :profile_image, class:"align-bottom" %></td>
          </tr>
          <tr class="form-group">
              <th><%= f.label :introduction, "自己紹介", class:"col-form-label" %></th>
              <td><%= f.text_area :introduction, class:"form-control" %></td>
          </tr>
          <tr class="actions text-center">
            <th colspan="2"><%= f.submit "編集を保存する", class: "btn  btn-danger w-100" %></th>
          </tr>
        <% end %>
        </table>
    </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10 my-3 rounded bg-primary">
        <h2><u><strong>会員一覧</strong></u></h2>
        <div class="row justify-content-center">
          <% @users.each do |user| %>
            <div class="card m-2" style="width: 18rem;">
              <div class="card-body">
                <div class="h5 card-title">
                  <%= link_to user_path(user.id) do %>
                    <%= user.name %>さん
                    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, class:"h-100 w-100 p-2", fallback: "l_e_others_501.png" %>
                  <% end %>
                </div>
                <% if user.introduction.present? %>
                  <p class="card-text"><%= truncate(user.introduction, length:25, line:0) %></p>
                <% else %>
                  <p class="card-text">紹介文考え中！！
                  </p>
                <% end %>
                <%= link_to "詳細を見る",  root_path, class: 'nav-link text-light btn mx-1' %>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <%= paginate @users %>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-4">
        <div class="p-md-2 mt-3 p-3 border border-light rounded bg-primary">
          <% if @user == current_user %>
            <h4>マイプロフィール</h4>
          <% else %>
            <h5><%= @user.name %>さんの<br>プロフィール</h5>
          <% end %>
          <div class="col-md-6">
            <%= attachment_image_tag @user, :profile_image, size: "150x150", fallback: "l_e_others_501.png" %>
          </div>
          <table class="table rounded border border-light">
            <tr>
              <td>名前</td>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <td>自己紹介</td>
              <th><%= @user.introduction %></th>
            </tr>
          </table>
          <div class="row justify-content-center">
            <% if @user == current_user %>
              <%= link_to "マイプロフィールを編集する", edit_user_path(current_user.id), class: "btn btn-danger w-75 mb-2"%>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-8 my-3 rounded bg-primary">
        <h2><u><strong><%= @user.name %>さんのレシピ</strong></u>(全<%= @allrecipes %>件)</h2>
        <div class="row justify-content-center">
          <% @user.recipes.each do |recipe| %>
            <div class="card m-2" style="width: 12rem;">
              <%= link_to recipe_path(recipe) do %>
                <%= attachment_image_tag recipe, :image, :fill, 100, 100, class:"h-100 w-100 p-2", fallback: "l_e_others_501.png" %>
              <% end %>
              <div class="card-body">
                <div class="h5 card-title"><%= recipe.title %></div>
                <p class="card-text"><%= truncate(recipe.impression, length:20) %></p>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</main>