config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }
  root to: "homes#top"
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    resources :recipe_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recipe_tags
  has_many :tags, through: :recipe_tags
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  attachment :image
  def tags_save(tag_list)
    if self.tags != nil
      recipe_tags_records = RecipeTag.where(recipe_id: self.id)
      recipe_tags_records.destroy_all
    end
    tag_list.each do |tag|
      inspected_tag = Tag.where(tag_name: tag).first_or_create
      self.tags << inspected_tag
    end

  end
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags
  has_many :recipes, through: :recipe_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
  has_many :recipe_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def set_search
    @search = Recipe.ransack(params[:q])
    @search_recipes = @search.result.page(params[:page]).reverse_order
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    recipe = Recipe.find(params[:recipe_id])
    favorite = current_user.favorites.new(recipe_id: recipe.id)
    favorite.save
    redirect_to recipe_path(recipe)
  end

  def destroy
    recipe = Recipe.find(params[:recipe_id])
    favorite = current_user.favorites.find_by(recipe_id: recipe.id)
    favorite.destroy
    redirect_to recipe_path(recipe)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @recipes = Recipe.last(4)
  end

end

app/controllers/recipe_comments_controller.rb
class RecipeCommentsController < ApplicationController
  def create
    recipe = Recipe.find(params[:recipe_id])
    comment = current_user.recipe_comments.new(recipe_comment_params)
    comment.recipe_id = recipe.id
    comment.save
    redirect_to recipe_path(recipe)
  end

  def destroy
    RecipeComment.find_by(id: params[:id]).destroy
    redirect_to recipe_path(params[:recipe_id])
  end
  private

  def recipe_comment_params
    params.require(:recipe_comment).permit(:comment, :rate)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end
  def index
    @recipes = Recipe.page(params[:page]).reverse_order
  end
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_tags = @recipe.tags
    @recipe_comment = RecipeComment.new
  end
  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
     render :edit
    else
     redirect_to recipes_path, notice: "ほかのユーザーのレシピは編集できません。"
    end
  end
  def update
    @recipe = Recipe.find(params[:id])
    tag_list = params[:recipe][:tag_names].split(",")
    @recipe.tags_save(tag_list)
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe.id), notice: "編集しました。"
  end
  def create
    @recipe = Recipe.new(recipe_params)
    tag_list = params[:recipe][:tag_names].split(nil)
    @recipe.tags_save(tag_list)
    @recipe.user_id = current_user.id
    @recipe.save
    redirect_to recipes_path, notice: "登録しました."
  end
  def delete
  end
  
  private
  def recipe_params
    params.require(:recipe).permit(:title, :image, :foodstuff, :instructions, :impression, :user_id)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @allrecipes = @user.recipes.count
  end
  def index
    @users = User.page(params[:page]).reverse_order
  end
  def edit
    @user = User.find(params[:id])
    if @user == current_user
     render :edit
    else
     redirect_to users_path, notice: "ほかのユーザー情報は編集できません。"
    end
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user), notice: "編集しました。"
  end
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipe_comments_helper.rb
module RecipeCommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JisuiFriend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to root_path do %>
            <%= image_tag('logo.png') %>
          <% end %>
          <div class="col-3 text-center"><dl class="searchbox">
  <%= search_form_for @search, url: recipes_path do |f| %>
    <dt><%= f.text_field :title_or_foodstuff_or_instructions_or_impression_cont ,placeholder: 'レシピタイトル検索' %></dt>
    <dd><%= f.submit ("検索") , class: 'search-btn'%></dd>
  <% end %>
</dl></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "レシピ一覧", recipes_path, class: 'nav-link text-light btn mx-1'%>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", users_path, class: 'nav-link text-light btn mx-1' %>
              </li>
              <li class="nav-item">
                <%= link_to "マイレシピ", user_path(current_user.id), class: 'nav-link text-light btn mx-1' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規投稿", new_recipe_path, class: 'nav-link text-light btn mx-1' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-light btn mx-1' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light btn mx-1' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン",  new_user_session_path, class: 'nav-link text-light btn mx-1' %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <p id="notice"><%= notice %></p>
    <%= yield %>
    </main>
    <footer>
      <div class="container mx-auto border-top border-dark">
        <div class="row">
          <div class="mx-auto py-5">
            <p>©2021 K.muramatsu</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>